### ISSUE TITLE
How to override nwgdmenu styles in css?

### ISSUE THREAD

**Issue by crabvk** [nwg-piotr/nwg-launchers#157]
I'd like to change nwgdmenu colors for the menu and selected items. What I found in current documentation allowed to change colors only partially

```css
#searchbox {
    background-color: #282c34;
}

label {
    background-color: #282c34;
}
```

<details>
  <summary>Screenshot</summary>
  <img alt="20210331_00h17m08s_grim" src="https://user-images.githubusercontent.com/3273827/113044009-a39d4300-91b6-11eb-8c8e-c88eb1aa7750.png">
</details>

**Comment by nwg-piotr** [comment]
GTK widgets we use here are `Menu` and `MenuItem`. You can apply styling to them e.g. like this:

```css
menu {
  background: #000
}


menuitem.hover {
  background: #0000FF
}
```
