### ISSUE TITLE
Set background color via style.css

### ISSUE THREAD

**Issue by scotabroad** [nwg-piotr/nwg-launchers#224]
For both nwggrid and nwgbar, the background can be set using the `-b` option, with the opacity also be defined by `-o`. However, as both nwggrid and nwgbar have `style.css` files, it would make more sense to set this there and not via command line options.

**Comment by scotabroad** [comment]
`nwgbar -b 000000 -o 0` or `nwgbar -b 00000000` both make it possible so that the color of the background is provided by the `.frame` attribute below to `nwgbar/style.css`.
```css
.frame {
  background: rgba (255, 255, 255, 0.5);
}
```
However, this does not seem like a good solution as it doesn't modify the window directly and requires making the window completely transparent. However, using any variation of the `window` attribute does not affect the window/background color.

**Comment by Siborgium** [comment]
Agreed. Honestly, specifying background color via arguments is kinda ugly. I'll look into it, but no hard promises :)

**Comment by scotabroad** [comment]
Thanks! I've also been trying to read up on how to do it. I've been looking into waybar how does it, as I've noticed it can take `window#waybar{}` to set the background color, though no equivalent CSS key currently exists for `nwggrid` or `nwgbar` that I could find. I'll keep you updated on anything else I find.

**Comment by Siborgium** [comment]
The following works
```css
window > box {
    background-color: #abcdef
}
```

but it's not pretty at all.

>`window#waybar`

This could be done by `set_name("waybar")` on the box.

**Comment by scotabroad** [comment]
Yes, I have seen that in the Waybar code here: [src/bar.cpp#L489](https://github.com/Alexays/Waybar/blob/94d6ae97410dd4bcc80c6ee8aaed3f5b1379d9e6/src/bar.cpp#L489) and have thought about adding something similar to `nwggrid` and `nwgbar`.

```css
window > box {
    background-color: rgba(123, 23, 45, 0.5)
}
```
does work with `nwggrid`, and I have been able to do the same with `nwgbar` using 
```css
window > scrolled window {
   background-color: rgba(123, 23, 45, 0.5)
 }
 ```
However, both need to be launched with the `-o 0` flag to get the opacity right, otherwise it overlays the color on top of the default one. Honestly, this is overall not too bad.
