### ISSUE TITLE
Feature: Change text color

### ISSUE THREAD

**Issue by MintyGitOut** [nwg-piotr/nwg-launchers#230]
A cool feature could be to allow users to change the color of text via a flag or CLI option. That's all

**Comment by Siborgium** [comment]
You can use CSS to change text color. I.e.
```css
button label {
  color: #123456;
}
```

I can think of certain usecases where using flags could be useful,
but all of them seem to be rather synthetic.
